### ISSUE TITLE
How did you do it?

### ISSUE THREAD

**Issue by nmital21** [shiena/Unity-PythonNet#1]
Hi, 
I'm trying to run python scripts from C# scripts associated with a Unity project. But I am not able to. The system gives me the following errors - 
"DllNotFoundException: Could not load Assets/Plugins/Python.Runtime.dll with flags RTLD_NOW | RTLD_GLOBAL: dlopen(Assets/Plugins/Python.Runtime.dll, 0x000A): tried: 'Assets/Plugins/Python.Runtime.dll' (not a mach-o file), ...."

Did you have the same problems? Could you tell me how you set up pythonnet on Unity? I would appreciate any help.

Best regards.

**Comment by shiena** [comment]
@nmital21 
Please refer to the following scripts and folders for initialization and runtime of Python.Net.

- https://github.com/shiena/Unity-PythonNet/blob/main/Assets/Scripts/PythonLifeCycle.cs
- https://github.com/shiena/Unity-PythonNet/tree/main/Assets/StreamingAssets

Although it is in Japanese, the procedure for building the environment is written [here](https://zenn.dev/shiena/articles/unity-python).
