### ISSUE TITLE
Integrate it in android / ios application (unity)

### ISSUE THREAD

**Issue by androidsparkling** [shiena/Unity-PythonNet#2]
Can you share the steps to integrate it to an Android or iOS unity application?

**Comment by shiena** [comment]
https://pythonnet.github.io/
> Python.NET (pythonnet) is a package that gives Python programmers nearly seamless integration with .NET Framework, .NET Core and Mono runtime on Windows, Linux and macOS.

Python.Net only supports Windows, Linux and macOS, so it probably won't work on Android, iOS.
Instead, the following libraries support Android and iOS.

- https://github.com/chaquo/chaquopy
- https://medium.com/swift2go/embedding-python-interpreter-inside-a-macos-app-and-publish-to-app-store-successfully-309be9fb96a5

**Comment by GeorgeGlyn** [comment]
Hi, can you help me to take a build for windows. I took a build and it is working on my system but when I shared it to others it is showing some python modules missing also in the log it is showing the cs file path as the path where the app is build not the path of the build folder?
