### ISSUE TITLE
webcam video

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [shiena/Unity-PythonNet#5]
How can I process webcam video with Python, and display it with Unity?

**Comment by shiena** [comment]
I think this can be done by combining the following processes.

- On the Python side, use OpenCV etc. to read the web camera video and load it into the texture.
- On the Unity side, external textures are loaded and displayed.

**Comment by Ishihara-Masabumi** [comment]
Thank you for your reply.
BTW, in tihs situation, what does texture mean?

**Comment by shiena** [comment]
In this case you should use one of the following:
- D3D11: ID3D11ShaderResourceView* or ID3D11Texture2D*
- D3D12: ID3D12Texture2D*
- OpenGL/OpenGL ES: GLuint

references: https://docs.unity3d.com/ScriptReference/Texture2D.CreateExternalTexture.html

**Comment by Ishihara-Masabumi** [comment]
After creating the texture, should I return it?

**Comment by shiena** [comment]
Sorry, please ask questions about coding on stackoverflow etc.
By the way, there is also a way to return binary data on the Python side and update the texture with LoadRawTextureData on the Unity side, as in this repository.

**Comment by Ishihara-Masabumi** [comment]
Thanks.
