### ISSUE TITLE
Error CS0656

### ISSUE THREAD

**Issue by Taryma-Zense** [shiena/Unity-PythonNet#6]
Hi, i'm facing a dependency problem
Assets\RandomPlot.cs(87,50): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
I did everything as described in the article on zenn.dev and at the startup stage of the project i got this error, can you help?

**Comment by shiena** [comment]
Please select .NET Framework in Api Compatibility Level. NET Standard 2.1 will not work.
![image](https://github.com/shiena/Unity-PythonNet/assets/1295639/3ffce647-3845-4d8e-88d3-1996282d1283)

**Comment by Taryma-Zense** [comment]
omg thank you very much!
